### ISSUE TITLE
Bad front-end

### ISSUE THREAD

**Issue by AyronRangel** [xoco70/kendozone#25]
Hi,

I follow your steps and when I tried to up the project appears (front-end) like this, can you help me to correct this "error"?

![image](https://user-images.githubusercontent.com/30760695/36099155-c3d5c3ca-0fe8-11e8-9435-0a8c2e13fc31.png)

**Comment by xoco70** [comment]
try 
```
npm run dev
```

**Comment by xoco70** [comment]
No news. Closing
