### ISSUE TITLE
[Installation] Artisan Migrate with postgresql

### ISSUE THREAD

**Issue by laurent-dumestier** [xoco70/kendozone#32]
Generate an error (windows, postgresql V10) : 

> php.exe artisan migrate

   Illuminate\Database\QueryException  : SQLSTATE[22P02]: Invalid text represent
ation: 7 ERREUR:  syntaxe en entr├®e invalide pour le type boolean : ┬½ 3 ┬╗ (SQ
L: create table "championship_settings" ("id" serial primary key not null, "alia
s" varchar(255) null, "championship_id" integer not null, "treeType" smallint no
t null default '1', "fightingAreas" smallint null default '1', "limitByEntity" i
nteger null, "hasPreliminary" boolean not null default '1', "preliminaryGroupSiz
e" boolean not null default '3', "preliminaryWinner" smallint not null default '
1', "preliminaryDuration" varchar(255) null, "teamSize" smallint null, "teamRese
rve" smallint null, "seedQuantity" smallint null, "hasEncho" boolean not null de
fault '1', "enchoQty" smallint not null default '0', "enchoDuration" varchar(255
) null, "hasHantei" boolean not null default '0', "cost" smallint null, "fightDu
ration" varchar(255) null, "hanteiLimit" smallint not null default '0', "enchoGo
ldPoint" smallint not null default '0', "created_at" timestamp(0) without time z
one null, "updated_at" timestamp(0) without time zone null, "deleted_at" timesta
mp(0) without time zone null))

  at E:\Project\kendozone\vendor\laravel\framework\src\Illuminate\Database\Conne
ction.php:664
    660|         // If an exception occurs when attempting to run a query, we'll
 format the error
    661|         // message to include the bindings with SQL, which will make th
is exception a
    662|         // lot more helpful to the developer instead of just the databa
se's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[22P02]: Invalid text represe
ntation: 7 ERREUR:  syntaxe en entr├®e invalide pour le type boolean : ┬½ 3 ┬╗")

      E:\Project\kendozone\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStat
ement.php:107

  2   PDOException::("SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  s
yntaxe en entr├®e invalide pour le type boolean : ┬½ 3 ┬╗")
      E:\Project\kendozone\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStat
ement.php:105

**Comment by xoco70** [comment]
Hi Laurent, 

System is designed to work with MySQL compatible databases.

With Laravel, you should be able to switch quickly between databases, but I guess it would be necessary to adapt migration scripts to fit in new format.
